spring:
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:13307/saju?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: admin1234
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      keepalive-time: 30000
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis  # 이 설정이 있어야 세션이 레디스로 갑니다!
    timeout: 30m
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.saju.api.**.dto
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
logging:
  level:
    jdbc.sqlonly: INFO    # SQL문만 출력
    jdbc.sqltiming: INFO  # SQL문과 실행시간 출력
    jdbc.resultsettable: INFO # 결과를 테이블 형태로 출력
    org.springframework.jdbc: DEBUG
    com.saju.api.mapper: DEBUG
    org.mybatis: DEBUG
file:
  upload-dir: C:/Users/c/Pictures/test/upload/
